addSbtPlugin("de.heikoseeberger" % "sbt-header"         % "5.9.0")
addSbtPlugin("com.github.sbt"    % "sbt-release"        % "1.1.0")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"      % "2.0.6")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"       % "2.5.0")
addSbtPlugin("ch.epfl.scala"     % "sbt-version-policy" % "2.1.0")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"       % "0.10.4")
