name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      MONGODB_URI: "mongodb://localhost:27017"

    steps:
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: 4.4
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v11
    - name: Run tests
      run: sbt test

